version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: monthly
    labels:
      - dependencies
      - go
      - Skip Changelog
    assignees:
      - "tillkuhn"
    open-pull-requests-limit: 6

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    rebase-strategy: "disabled"     # Disable rebasing for GH actions
    schedule:
      interval: "monthly"
