version: "2"
run:
  issues-exit-code: 1
  tests: true
linters:
  enable:
    - cyclop
    - dogsled
    - dupl
    - err113
    - errorlint
    - exhaustive
    - funlen
    - gochecknoglobals
    - goconst
    - gocritic
    - gocyclo
    - goprintffuncname
    - gosec
    - misspell
    - mnd
    - nakedret
    - nestif
    - nilerr
    - noctx
    - nolintlint
    - prealloc
    - promlinter
    - revive
    - unconvert
    - unparam
    - whitespace
  settings:
    funlen:
      lines: 100
      statements: 50
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - funlen
          - gochecknoglobals
          - gosec
          - noctx
        path: _test\.go
      - linters:
          - gochecknoglobals
        path: main.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
